### ISSUE TITLE
cpp version of geographiclib

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/geographiclib-feedstock#4]
Hi @QuLogic @cffk @ocefpaf,

For our efforts on ROS on conda (see https://github.com/RoboStack/ros-noetic), we require the C++ version of Geographiclib (https://sourceforge.net/projects/geographiclib/) as this is a dependency of https://github.com/cra-ros-pkg/robot_localization

It would be great if you could make this version available :).

/cc @wolfv @traversaro

**Comment by cffk** [comment]
I started doing exactly this a couple of weeks back.  I'll try to complete this by the end of next week.  It'll probably be called geographiclib-cpp.

**Comment by Tobias-Fischer** [comment]
Awesome, that sounds great!

**Comment by wolfv** [comment]
cool! Thanks @cffk & let me know if I can help.

**Comment by ocefpaf** [comment]
I'm not sure on what we should do. Is it just a flag/build option? Or a replacement implementation?

**Comment by cffk** [comment]
I've made this [pull request](https://github.com/conda-forge/staged-recipes/pull/13650) for `geographiclib-cxx` on `conda-forge/staged-recipes`.  Given that `geographiclib-feedstock` is focused on just the python implementation of the geodesic routines, it makes sense to have the C++ library + utilities be a separate feedstock.  I think `geographiclib-cxx` is ready to be deployed.  However, this is my first foray into condo feedstocks and I'd appreciate it if others can give it a once over.

**Comment by ocefpaf** [comment]
That looks like the right approach. I'll check you PR to staged-recipes in a moment.

**Comment by ocefpaf** [comment]
@cffk let's close this and follow up in the staged-recipes PR.
